id: scheduled-health-check
namespace: ai-devops
description: Periodic health check for deployed applications

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *" # Every 30 minutes

tasks:
  - id: check_backend_health
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - |
        response=$(curl -s -w "%{http_code}" http://localhost:3000/health)
        if [ "$response" != "200" ]; then
          echo "Backend health check failed!"
          exit 1
        fi
        echo "Backend is healthy"

  - id: check_database
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - echo "Checking database connection..."
      - mongosh --eval "db.adminCommand('ping')" || exit 1
      - echo "Database is healthy"

  - id: check_redis
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - redis-cli ping || exit 1
      - echo "Redis is healthy"

errors:
  - id: alert_on_failure
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK_URL') }}"
    payload: |
      {
        "text": "🚨 Health Check Failed - System Alert!"
      }
